INFO 2020-04-16 15:40:02,305 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:14:11,030 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:14:43,556 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 17:15:25,512 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 18:06:54,643 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-16 18:07:10,716 log 228 Not Found: /
WARNING 2020-04-16 18:07:10,717 basehttp 154 "GET / HTTP/1.1" 404 2129
WARNING 2020-04-16 18:07:10,803 log 228 Not Found: /favicon.ico
WARNING 2020-04-16 18:07:10,804 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2180
INFO 2020-04-16 18:54:43,369 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:24:19,987 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:24:57,690 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:28:16,412 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:29:00,031 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-16 19:29:00,873 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:56:55,069 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 19:57:45,896 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:01:34,272 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:09:29,115 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:16:43,111 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:21:36,258 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:24:27,597 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:27:42,578 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-04-16 20:27:43,000 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:34:03,842 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-16 20:34:04,315 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:43:35,529 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:43:49,142 basehttp 154 "GET /usernames/sfdgrgh/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:43:59,659 log 228 Not Found: /carts/simple/
WARNING 2020-04-16 20:43:59,666 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2183
WARNING 2020-04-16 20:44:01,577 log 228 Not Found: /image_codes/8a5c35d5-08d6-4743-9e6d-57d83b8f4859/
WARNING 2020-04-16 20:44:01,579 basehttp 154 "GET /image_codes/8a5c35d5-08d6-4743-9e6d-57d83b8f4859/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:44:12,038 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:13,689 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:21,167 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:23,257 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:28,865 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:33,042 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:40,958 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:44:48,774 basehttp 154 "GET /usernames/jflwskdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:44:56,545 log 228 Not Found: /image_codes/b9805de3-cb23-4f0a-b1c2-cdaabec64311/
WARNING 2020-04-16 20:44:56,547 basehttp 154 "GET /image_codes/b9805de3-cb23-4f0a-b1c2-cdaabec64311/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:44:58,447 log 228 Not Found: /image_codes/c7f45a9b-dca5-4eed-bb42-eb0dec4c0316/
WARNING 2020-04-16 20:44:58,449 basehttp 154 "GET /image_codes/c7f45a9b-dca5-4eed-bb42-eb0dec4c0316/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:45:00,425 log 228 Not Found: /image_codes/bd44dbf5-5ae9-4360-98ec-7ebcb44fe4a4/
WARNING 2020-04-16 20:45:00,429 basehttp 154 "GET /image_codes/bd44dbf5-5ae9-4360-98ec-7ebcb44fe4a4/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:45:04,210 basehttp 154 "GET /usernames/regerryt/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:45:31,215 log 228 Not Found: /image_codes/ec90d94b-15aa-47aa-9043-e84c976ccad7/
WARNING 2020-04-16 20:45:31,217 basehttp 154 "GET /image_codes/ec90d94b-15aa-47aa-9043-e84c976ccad7/ HTTP/1.1" 404 2291
WARNING 2020-04-16 20:45:33,187 log 228 Not Found: /image_codes/c9f8b034-6f0a-463b-97ec-e3dbdf196987/
WARNING 2020-04-16 20:45:33,191 basehttp 154 "GET /image_codes/c9f8b034-6f0a-463b-97ec-e3dbdf196987/ HTTP/1.1" 404 2291
INFO 2020-04-16 20:45:39,193 basehttp 154 "GET /usernames/sdgwet/count/ HTTP/1.1" 200 39
INFO 2020-04-16 20:46:41,061 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 20:47:35,032 basehttp 154 "GET /usernames/jolfiej/count/ HTTP/1.1" 200 39
WARNING 2020-04-16 20:47:35,085 log 228 Not Found: /favicon.ico
WARNING 2020-04-16 20:47:35,087 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2171
INFO 2020-04-16 20:56:33,531 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 21:02:06,516 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-16 21:02:09,054 basehttp 154 "GET /mobiles/14111111111/count/ HTTP/1.1" 200 39
INFO 2020-04-20 16:23:06,989 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:24:24,588 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:24:40,903 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 16:32:49,670 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:57:52,490 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:10,006 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 17:58:10,427 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:21,484 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 17:58:32,560 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 17:58:35,691 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:00:25,361 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:00:36,024 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:01:08,693 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:01:10,898 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:05:07,217 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:05:07,597 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:05:10,572 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:08:17,921 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:10:43,431 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:05,252 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 18:11:07,158 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:47,488 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-20 18:11:49,448 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:11:57,469 basehttp 154 "GET /usernames/sadgfdg/count/ HTTP/1.1" 200 39
INFO 2020-04-20 18:12:11,760 basehttp 154 "GET /mobiles/13111111111/count/ HTTP/1.1" 200 39
WARNING 2020-04-20 18:12:40,637 log 228 Not Found: /image_codes/c978fd7b-8183-4bc8-841e-33dfd4abc50e/
WARNING 2020-04-20 18:12:40,638 basehttp 154 "GET /image_codes/c978fd7b-8183-4bc8-841e-33dfd4abc50e/ HTTP/1.1" 404 2667
WARNING 2020-04-20 18:12:41,323 log 228 Not Found: /image_codes/f23c9a80-63e6-4f95-b47b-c7f6ac695fbd/
WARNING 2020-04-20 18:12:41,328 basehttp 154 "GET /image_codes/f23c9a80-63e6-4f95-b47b-c7f6ac695fbd/ HTTP/1.1" 404 2667
WARNING 2020-04-20 18:12:42,239 log 228 Not Found: /image_codes/9db2c29d-b66d-42d6-8919-b976844f09d1/
WARNING 2020-04-20 18:12:42,242 basehttp 154 "GET /image_codes/9db2c29d-b66d-42d6-8919-b976844f09d1/ HTTP/1.1" 404 2667
INFO 2020-04-20 18:23:03,055 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-20 18:23:03,468 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-20 18:23:08,713 log 228 Internal Server Error: /image_codes/3bf9d355-e4a3-4fe5-8c10-a83fb71b3092/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:08,714 basehttp 154 "GET /image_codes/3bf9d355-e4a3-4fe5-8c10-a83fb71b3092/ HTTP/1.1" 500 83882
ERROR 2020-04-20 18:23:17,843 log 228 Internal Server Error: /image_codes/cf5f76a2-ad3c-4494-9309-6173f33817ef/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:17,845 basehttp 154 "GET /image_codes/cf5f76a2-ad3c-4494-9309-6173f33817ef/ HTTP/1.1" 500 83882
ERROR 2020-04-20 18:23:19,120 log 228 Internal Server Error: /image_codes/ae11266d-63b7-466e-a622-add43dfa9e70/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:23:19,121 basehttp 154 "GET /image_codes/ae11266d-63b7-466e-a622-add43dfa9e70/ HTTP/1.1" 500 83882
INFO 2020-04-20 18:46:46,357 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-20 18:46:51,356 log 228 Internal Server Error: /image_codes/8398141b-7acf-4167-935f-c233a250815e/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py", line 12, in get
    text, image = captcha.generate_captche()
AttributeError: 'Captcha' object has no attribute 'generate_captche'
ERROR 2020-04-20 18:46:51,358 basehttp 154 "GET /image_codes/8398141b-7acf-4167-935f-c233a250815e/ HTTP/1.1" 500 83882
INFO 2020-04-20 18:52:19,714 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 18:52:22,830 basehttp 154 "GET /image_codes/e9bd0bd3-636d-4e67-b9a2-f19fef406bf6/ HTTP/1.1" 200 2869
INFO 2020-04-20 20:27:04,793 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:27:10,411 basehttp 154 "GET /image_codes/d1c1e70b-701a-4459-b904-1cdbd0aebfaf/ HTTP/1.1" 200 3212
INFO 2020-04-20 20:27:11,790 basehttp 154 "GET /image_codes/016b5c25-7e59-4faa-a3f0-1455e68d06b1/ HTTP/1.1" 200 3072
INFO 2020-04-20 20:27:12,479 basehttp 154 "GET /image_codes/094c6dde-c0b7-431f-8b38-b5fd1a7dcc04/ HTTP/1.1" 200 3218
INFO 2020-04-20 20:27:13,088 basehttp 154 "GET /image_codes/7d9bb812-f640-4bf4-a45f-f15d29033bd4/ HTTP/1.1" 200 3310
INFO 2020-04-20 20:27:13,762 basehttp 154 "GET /image_codes/745773f7-674e-469e-a4f4-60b3a8be3bac/ HTTP/1.1" 200 2933
INFO 2020-04-20 20:31:32,275 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:32,687 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:31:41,521 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:41,922 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:31:50,729 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:31:51,109 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:32:20,587 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:32:20,999 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:32:33,051 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-20 20:32:33,508 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-20 20:40:48,932 basehttp 154 "GET /image_codes/63d3c5fb-e355-4cb9-b1d7-fc5d74153ca2/ HTTP/1.1" 200 3345
INFO 2020-04-20 20:41:09,777 basehttp 154 "GET /image_codes/6ce2946b-e54e-4b3d-af96-c4f63a30b610/ HTTP/1.1" 200 2941
INFO 2020-04-20 20:41:11,127 basehttp 154 "GET /image_codes/3bd45479-6b89-4bb1-90f6-260d45abae19/ HTTP/1.1" 200 3141
INFO 2020-04-20 20:41:13,165 basehttp 154 "GET /image_codes/24d3058b-b683-49c3-a8a7-0028ac97c5b3/ HTTP/1.1" 200 3565
INFO 2020-04-20 20:41:14,262 basehttp 154 "GET /image_codes/189e3c8e-a77b-4f93-a277-ef1a49f48024/ HTTP/1.1" 200 3033
INFO 2020-04-21 11:37:56,900 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:36,387 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/views.py changed, reloading.
INFO 2020-04-21 11:38:39,198 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:51,344 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/verifications/urls.py changed, reloading.
INFO 2020-04-21 11:38:51,764 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:38:54,228 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:39:02,428 basehttp 154 "GET /image_codes/1f107da4-0dcf-46e1-a63d-5522769e9c5f/ HTTP/1.1" 200 2967
INFO 2020-04-21 11:39:17,448 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:39:36,007 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:39:46,638 basehttp 154 "GET /sms_codes/13652421005/?image_code=q60i&image_code_id=1f107da4-0dcf-46e1-a63d-5522769e9c5f HTTP/1.1" 200 63
INFO 2020-04-21 11:39:46,647 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:43:57,021 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 11:44:01,924 basehttp 154 "GET /image_codes/eb35ad4c-095d-4508-a742-29c0b172d22c/ HTTP/1.1" 200 3300
INFO 2020-04-21 11:44:07,617 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:08,149 basehttp 154 "GET /sms_codes/13652421005/?image_code=wzvf&image_code_id=eb35ad4c-095d-4508-a742-29c0b172d22c HTTP/1.1" 200 61
INFO 2020-04-21 11:44:41,333 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:41,339 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:41,349 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
WARNING 2020-04-21 11:44:41,363 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:41,364 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:42,482 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:42,487 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:42,491 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:42,491 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,124 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,126 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,130 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,132 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,556 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,560 log 228 Not Found: /register/
INFO 2020-04-21 11:44:43,561 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,561 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:43,835 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,841 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,847 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,848 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:43,990 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:43,996 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:43,997 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:43,998 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,160 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,165 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:44,169 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,178 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 11:44:44,327 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,328 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:44:44,334 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,334 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,498 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 11:44:44,498 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 11:44:44,503 log 228 Not Found: /register/
WARNING 2020-04-21 11:44:44,506 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 11:45:46,907 basehttp 154 "GET /sms_codes/13652421005/?image_code=wzvf&image_code_id=eb35ad4c-095d-4508-a742-29c0b172d22c HTTP/1.1" 200 69
INFO 2020-04-21 11:45:46,911 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:18,112 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 12:01:23,633 basehttp 154 "GET /image_codes/c6b4c67c-bf08-4454-8c25-b9929ce5c40c/ HTTP/1.1" 200 3387
INFO 2020-04-21 12:01:28,156 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:37,767 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:43,367 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:01:43,922 basehttp 154 "GET /sms_codes/13652421005/?image_code=opz8&image_code_id=c6b4c67c-bf08-4454-8c25-b9929ce5c40c HTTP/1.1" 200 61
INFO 2020-04-21 12:02:02,525 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:02,528 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,786 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,788 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:04,791 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
WARNING 2020-04-21 12:02:04,805 log 228 Not Found: /register/
WARNING 2020-04-21 12:02:04,806 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
WARNING 2020-04-21 12:02:05,913 log 228 Not Found: /register/
INFO 2020-04-21 12:02:05,917 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 12:02:05,917 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
WARNING 2020-04-21 12:02:05,919 basehttp 154 "POST /register/ HTTP/1.1" 404 2738
INFO 2020-04-21 13:05:17,570 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-21 13:05:47,956 log 228 Not Found: /carts/simple/
WARNING 2020-04-21 13:05:47,957 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-04-21 13:05:50,308 basehttp 154 "GET /image_codes/fcc9c72e-4d77-4a47-9c23-7359fdf3d48d/ HTTP/1.1" 200 3517
INFO 2020-04-21 13:05:54,874 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:05,398 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:11,518 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:06:11,674 basehttp 154 "GET /sms_codes/13652421005/?image_code=tgmd&image_code_id=fcc9c72e-4d77-4a47-9c23-7359fdf3d48d HTTP/1.1" 200 61
INFO 2020-04-21 13:07:13,106 basehttp 154 "GET /image_codes/e6b48d5f-7881-4cd2-a428-fd5edb59713c/ HTTP/1.1" 200 3455
INFO 2020-04-21 13:07:26,460 basehttp 154 "GET /sms_codes/13652421005/?image_code=ebyj&image_code_id=e6b48d5f-7881-4cd2-a428-fd5edb59713c HTTP/1.1" 200 61
INFO 2020-04-21 13:07:26,462 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:08:31,718 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:08:31,723 basehttp 154 "GET /sms_codes/13652421005/?image_code=ebyj&image_code_id=e6b48d5f-7881-4cd2-a428-fd5edb59713c HTTP/1.1" 200 69
INFO 2020-04-21 13:11:25,161 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:09,577 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:24,970 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/celery_tasks/sms/tasks.py changed, reloading.
INFO 2020-04-21 13:13:25,403 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:27,287 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:13:51,540 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:17:21,250 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:20:10,815 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:21:42,212 autoreload 217 /home/ubuntu/Desktop/django/hfad_python/meiduo_mall/meiduo_mall/celery_tasks/sms/yuntongxun/ccp_sms.py changed, reloading.
INFO 2020-04-21 13:21:42,651 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-21 13:21:53,570 log 228 Not Found: /carts/simple/
WARNING 2020-04-21 13:21:53,572 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2749
INFO 2020-04-21 13:21:55,773 basehttp 154 "GET /image_codes/a7772438-29f6-4138-9c99-c2026779ed1b/ HTTP/1.1" 200 3001
INFO 2020-04-21 13:21:58,364 basehttp 154 "GET /usernames/jfhsalkdjf/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:06,449 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:11,787 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-21 13:22:11,921 basehttp 154 "GET /sms_codes/13652421005/?image_code=ihsk&image_code_id=a7772438-29f6-4138-9c99-c2026779ed1b HTTP/1.1" 200 61
INFO 2020-04-21 13:42:14,018 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:42:42,935 basehttp 154 "GET /admin/ HTTP/1.1" 302 0
INFO 2020-04-21 13:42:42,999 basehttp 154 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
INFO 2020-04-21 13:42:43,153 basehttp 154 "GET /static/admin/css/base.css HTTP/1.1" 200 16378
INFO 2020-04-21 13:42:43,160 basehttp 154 "GET /static/admin/css/login.css HTTP/1.1" 200 1233
INFO 2020-04-21 13:42:43,164 basehttp 154 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17944
INFO 2020-04-21 13:42:43,188 basehttp 154 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
WARNING 2020-04-21 13:42:43,390 log 228 Not Found: /favicon.ico
WARNING 2020-04-21 13:42:43,392 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2737
INFO 2020-04-21 13:42:43,394 basehttp 154 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2020-04-21 13:42:43,398 basehttp 154 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2020-04-21 13:42:52,791 basehttp 154 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 1980
INFO 2020-04-21 13:42:52,894 basehttp 154 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2020-04-21 13:48:27,610 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-21 13:48:35,465 basehttp 154 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2020-04-21 13:48:35,517 basehttp 154 "GET /admin/ HTTP/1.1" 200 3289
INFO 2020-04-21 13:48:35,603 basehttp 154 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
INFO 2020-04-21 13:48:35,611 basehttp 154 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2020-04-21 13:48:35,627 basehttp 154 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2020-04-21 13:48:43,431 basehttp 154 "GET /admin/users/user/add/ HTTP/1.1" 200 13275
INFO 2020-04-21 13:48:43,464 basehttp 154 "GET /static/admin/css/forms.css HTTP/1.1" 200 8518
INFO 2020-04-21 13:48:43,501 basehttp 154 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
INFO 2020-04-21 13:48:43,525 basehttp 154 "GET /admin/jsi18n/ HTTP/1.1" 200 3223
INFO 2020-04-21 13:48:43,527 basehttp 154 "GET /static/admin/js/calendar.js HTTP/1.1" 200 7777
INFO 2020-04-21 13:48:43,528 basehttp 154 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
INFO 2020-04-21 13:48:43,531 basehttp 154 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20218
INFO 2020-04-21 13:48:43,532 basehttp 154 "GET /static/admin/js/core.js HTTP/1.1" 200 7099
INFO 2020-04-21 13:48:43,542 basehttp 154 "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
INFO 2020-04-21 13:48:43,546 basehttp 154 "GET /static/admin/js/urlify.js HTTP/1.1" 200 8941
INFO 2020-04-21 13:48:43,547 basehttp 154 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271817
INFO 2020-04-21 13:48:43,553 basehttp 154 "GET /static/admin/js/actions.js HTTP/1.1" 200 6766
INFO 2020-04-21 13:48:43,559 basehttp 154 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
INFO 2020-04-21 13:48:43,582 basehttp 154 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
INFO 2020-04-21 13:48:43,597 basehttp 154 "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
INFO 2020-04-21 13:48:43,598 basehttp 154 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
INFO 2020-04-21 13:48:43,778 basehttp 154 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2020-04-21 13:48:43,787 basehttp 154 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2020-04-21 13:49:01,301 basehttp 154 "GET /admin/ HTTP/1.1" 200 3289
INFO 2020-04-22 03:03:32,292 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:09:05,905 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:18:41,890 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:22:27,303 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:24:31,364 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:25:06,235 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:33:35,068 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:35:58,729 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:36:05,608 basehttp 154 "GET /image_codes/cb75999c-9b71-4fc3-b82e-7d9bd977c2e8/ HTTP/1.1" 200 3192
INFO 2020-04-22 03:36:13,705 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:13,878 basehttp 154 "GET /sms_codes/13652421005/?image_code=xhko&image_code_id=cb75999c-9b71-4fc3-b82e-7d9bd977c2e8 HTTP/1.1" 200 61
INFO 2020-04-22 03:36:49,045 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2020-04-22 03:36:49,111 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:49,123 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
ERROR 2020-04-22 03:36:49,131 log 228 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 42, in post
    if not all(username, password, password2, mobile, allow, sms_code_client):
TypeError: all() takes exactly one argument (6 given)
ERROR 2020-04-22 03:36:49,135 basehttp 154 "POST /register/ HTTP/1.1" 500 84267
INFO 2020-04-22 03:36:52,657 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:36:52,661 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
ERROR 2020-04-22 03:36:52,694 log 228 Internal Server Error: /register/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 42, in post
    if not all(username, password, password2, mobile, allow, sms_code_client):
TypeError: all() takes exactly one argument (6 given)
ERROR 2020-04-22 03:36:52,695 basehttp 154 "POST /register/ HTTP/1.1" 500 84267
INFO 2020-04-22 03:41:13,775 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 03:41:18,171 basehttp 154 "GET /image_codes/aaf196cf-931a-4bc1-8cad-1d28a6335803/ HTTP/1.1" 200 3456
INFO 2020-04-22 03:41:29,854 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:30,005 basehttp 154 "GET /sms_codes/13652421005/?image_code=cqer&image_code_id=aaf196cf-931a-4bc1-8cad-1d28a6335803 HTTP/1.1" 200 61
INFO 2020-04-22 03:41:52,840 basehttp 154 "GET /usernames/meihao/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:52,840 basehttp 154 "GET /mobiles/13652421005/count/ HTTP/1.1" 200 39
INFO 2020-04-22 03:41:53,082 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2020-04-22 03:41:53,626 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 03:41:53,631 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2907
INFO 2020-04-22 04:06:29,486 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:07:11,349 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 04:07:11,441 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:07:11,443 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:07:35,970 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:07:47,453 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:08:07,838 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-22 04:08:17,446 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:08:17,449 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
ERROR 2020-04-22 04:08:18,356 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:08:18,357 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:11:14,727 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 04:11:23,707 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:11:23,709 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:11:42,598 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 04:11:42,672 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:11:42,673 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:12:33,822 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-22 04:12:36,943 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 82, in post
    dict = json.load(request.body.decode())
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
ERROR 2020-04-22 04:12:36,944 basehttp 154 "POST /login/ HTTP/1.1" 500 87877
INFO 2020-04-22 04:15:52,316 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 04:15:55,628 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 04:15:56,083 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:15:56,084 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:27:37,166 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 04:28:23,787 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:23,789 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 04:28:33,092 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 04:28:33,239 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 04:28:33,644 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:33,645 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
WARNING 2020-04-22 04:28:44,277 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 04:28:44,278 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:42:31,436 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 05:42:37,749 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:42:37,750 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:42:52,883 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
ERROR 2020-04-22 05:42:52,939 log 228 Internal Server Error: /login/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/utils/module_loading.py", line 20, in import_string
    return getattr(module, class_name)
AttributeError: module 'users.utils' has no attribute 'UsernameMobileAuthBackend'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 91, in post
    user = authenticate(username=username, password=password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 66, in authenticate
    for backend, backend_path in _get_backends(return_tuples=True):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
    backend = load_backend(backend_path)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
    return import_string(path)()
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/utils/module_loading.py", line 24, in import_string
    ) from err
ImportError: Module "users.utils" does not define a "UsernameMobileAuthBackend" attribute/class
ERROR 2020-04-22 05:42:52,941 basehttp 154 "POST /login/ HTTP/1.1" 500 104959
INFO 2020-04-22 05:43:59,896 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:44:03,220 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 05:44:03,674 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:44:03,677 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:45:33,775 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:46:41,553 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 05:46:46,141 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 05:46:46,266 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 05:46:46,778 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:46:46,779 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:47:34,530 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 05:47:40,756 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 05:47:40,760 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 05:47:43,835 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 05:48:44,978 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:16:54,031 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-22 06:16:55,408 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:18:01,966 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:18:36,497 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:20:22,401 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:22:29,363 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 06:22:36,152 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 06:22:36,310 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 06:22:36,770 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 06:22:36,770 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3062
INFO 2020-04-22 07:16:48,919 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 07:16:55,415 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:16:55,416 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:16:59,949 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 07:16:59,983 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 07:17:19,332 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 07:17:22,320 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 07:17:22,457 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 07:17:22,890 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:17:22,892 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:17:31,993 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 07:18:12,215 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 07:18:12,898 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 07:18:12,905 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3218
INFO 2020-04-22 07:18:35,538 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 09:12:28,085 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 09:12:40,662 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 09:12:40,664 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-04-22 09:12:44,107 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 09:12:44,254 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 09:12:44,657 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 09:12:44,658 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3372
INFO 2020-04-22 09:12:48,242 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 14:12:44,408 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 14:12:50,395 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 14:12:50,419 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 14:12:53,692 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:04:06,164 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 19:04:57,091 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/oauth/utils.py changed, reloading.
INFO 2020-04-22 19:04:57,526 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 19:05:00,717 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:05:25,961 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:05:25,962 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:05:38,974 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:06:18,737 basehttp 154 "GET /oauth_callback/?code=F0A13719D65885585D82415D4518F262 HTTP/1.1" 200 263
INFO 2020-04-22 19:06:18,815 basehttp 154 "GET /image_codes/fa40a9ec-98b0-4c4d-8fb8-31bf8813542a/ HTTP/1.1" 200 3485
INFO 2020-04-22 19:06:45,406 basehttp 154 "GET /sms_codes/13652421005/?image_code=mwvo&image_code_id=fa40a9ec-98b0-4c4d-8fb8-31bf8813542a HTTP/1.1" 200 61
INFO 2020-04-22 19:07:06,785 basehttp 154 "OPTIONS /oauth_callback/ HTTP/1.1" 200 0
INFO 2020-04-22 19:07:06,962 basehttp 154 "POST /oauth_callback/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:07:07,569 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:07:07,570 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:07:26,666 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 19:07:26,671 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 19:07:26,734 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 19:07:26,737 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 19:07:40,569 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 19:07:40,592 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 19:07:44,405 basehttp 154 "GET /qq/authorization/?next=/ HTTP/1.1" 200 203
INFO 2020-04-22 19:07:59,881 basehttp 154 "GET /oauth_callback/?code=F6F582B7A47FF2854CEB670A60A9FAAE HTTP/1.1" 200 27
WARNING 2020-04-22 19:08:00,359 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:08:00,360 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:10:58,344 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:10:58,346 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:11:36,792 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:11:36,793 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:11:38,261 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 19:11:38,294 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:11:47,714 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:11:47,715 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:12:00,996 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:12:00,997 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:12:55,158 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:12:55,163 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:13:02,361 log 228 Not Found: /carts/
WARNING 2020-04-22 19:13:02,362 basehttp 154 "GET /carts/ HTTP/1.1" 404 3681
INFO 2020-04-22 19:13:05,575 basehttp 154 "OPTIONS /carts/selection/ HTTP/1.1" 200 0
WARNING 2020-04-22 19:13:05,585 log 228 Not Found: /carts/selection/
WARNING 2020-04-22 19:13:05,587 basehttp 154 "PUT /carts/selection/ HTTP/1.1" 404 3711
WARNING 2020-04-22 19:13:49,594 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:13:49,595 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:16:01,179 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:16:12,256 log 228 Not Found: /
WARNING 2020-04-22 19:16:12,258 basehttp 154 "GET / HTTP/1.1" 404 3639
WARNING 2020-04-22 19:16:12,366 log 228 Not Found: /favicon.ico
WARNING 2020-04-22 19:16:12,370 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 3690
WARNING 2020-04-22 19:16:22,281 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:16:22,289 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:16:30,723 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:16:30,725 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:17:20,419 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:17:20,420 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 19:18:07,904 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:18:07,905 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:55:10,502 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 19:55:17,648 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:55:17,648 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:55:30,969 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 19:55:31,102 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:55:31,516 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:55:31,517 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-22 19:59:36,470 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-22 19:59:45,758 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 19:59:46,204 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 19:59:46,206 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:09,339 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:09,340 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:18,248 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:01:18,252 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:01:18,299 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:01:18,301 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:01:21,335 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 20:01:21,461 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:01:21,912 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:21,912 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:01:23,931 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:01:23,942 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:01:24,008 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:01:24,012 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:01:31,515 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:01:31,946 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:01:31,947 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:02:12,407 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:02:12,408 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:02:12,469 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:02:12,470 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
WARNING 2020-04-22 20:09:58,750 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:09:58,762 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:09:58,894 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:09:58,897 basehttp 154 "GET /info/ HTTP/1.1" 500 74312
INFO 2020-04-22 20:13:16,410 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:13:21,816 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-22 20:13:21,952 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:13:22,390 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:13:22,391 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3714
WARNING 2020-04-22 20:13:23,982 log 228 Not Found: /info/
WARNING 2020-04-22 20:13:23,985 basehttp 154 "GET /info/ HTTP/1.1" 404 3690
WARNING 2020-04-22 20:13:23,994 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:13:23,995 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3726
INFO 2020-04-22 20:15:16,049 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:15:16,770 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:15:16,774 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:16:18,763 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-22 20:16:19,567 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:18:29,388 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-04-22 20:18:29,429 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-04-22 20:18:32,804 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:18:33,334 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:18:33,336 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:18:49,575 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:18:49,581 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:18:49,626 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:18:49,628 basehttp 154 "GET /info/ HTTP/1.1" 500 74312
WARNING 2020-04-22 20:19:45,550 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:19:45,554 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
ERROR 2020-04-22 20:19:45,608 log 228 Internal Server Error: /info/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/utils/view.py", line 6, in wrapper
    if request.usr.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'usr'
ERROR 2020-04-22 20:19:45,610 basehttp 154 "GET /info/ HTTP/1.1" 500 74282
INFO 2020-04-22 20:22:06,516 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-22 20:22:10,033 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:22:10,036 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:22:10,055 basehttp 154 "GET /info/ HTTP/1.1" 200 125
INFO 2020-04-22 20:23:05,397 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-22 20:23:09,494 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-22 20:23:09,955 log 228 Not Found: /carts/simple/
WARNING 2020-04-22 20:23:09,957 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-22 20:23:11,890 log 228 Not Found: /browse_histories/
WARNING 2020-04-22 20:23:11,892 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-04-22 20:23:11,909 basehttp 154 "GET /info/ HTTP/1.1" 200 125
INFO 2020-04-27 04:10:43,023 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:11:11,140 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 04:11:18,217 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 04:11:18,221 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
INFO 2020-04-27 04:11:23,903 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 04:11:24,051 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 04:11:24,485 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 04:11:24,487 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3702
WARNING 2020-04-27 04:11:27,062 log 228 Not Found: /browse_histories/
INFO 2020-04-27 04:11:27,084 basehttp 154 "GET /info/ HTTP/1.1" 200 125
WARNING 2020-04-27 04:11:27,096 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3714
INFO 2020-04-27 04:11:56,283 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
WARNING 2020-04-27 04:11:56,304 log 228 Not Found: /emails/
WARNING 2020-04-27 04:11:56,304 basehttp 154 "PUT /emails/ HTTP/1.1" 404 3684
INFO 2020-04-27 04:13:22,477 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-27 04:13:23,788 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:13:49,050 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 04:14:25,899 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 171, in put
    verify_url = request.user.generate_access_token()
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py", line 35, in generate_access_token
    return dev.EMAIL_VERIFY_URL + obj
TypeError: must be str, not TimedJSONWebSignatureSerializer
INFO 2020-04-27 04:19:49,726 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:20:21,453 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 04:20:29,468 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 04:20:29,471 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3858
WARNING 2020-04-27 04:20:33,003 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 04:20:33,012 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3870
INFO 2020-04-27 04:20:33,016 basehttp 154 "GET /info/ HTTP/1.1" 200 151
INFO 2020-04-27 04:20:52,932 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2020-04-27 04:20:53,005 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 171, in put
    verify_url = request.user.generate_access_token()
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py", line 35, in generate_access_token
    return dev.EMAIL_VERIFY_URL + obj
TypeError: must be str, not TimedJSONWebSignatureSerializer
ERROR 2020-04-27 04:20:53,006 basehttp 154 "PUT /emails/ HTTP/1.1" 500 85486
INFO 2020-04-27 04:23:12,036 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:23:13,257 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 04:23:13,375 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 04:23:13,850 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 04:23:13,852 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3858
WARNING 2020-04-27 04:23:17,114 log 228 Not Found: /browse_histories/
INFO 2020-04-27 04:23:17,115 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 04:23:17,127 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3870
INFO 2020-04-27 04:50:37,898 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:50:41,328 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 04:50:41,443 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 04:50:41,910 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 04:50:41,915 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
INFO 2020-04-27 04:50:43,332 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 04:50:43,337 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 04:50:43,338 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-04-27 04:51:28,172 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2020-04-27 04:51:28,242 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 172, in put
    verify_url = request.user.generate_access_token()
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py", line 35, in generate_access_token
    return dev.EMAIL_VERIFY_URL + obj
TypeError: must be str, not TimedJSONWebSignatureSerializer
ERROR 2020-04-27 04:51:28,246 basehttp 154 "PUT /emails/ HTTP/1.1" 500 89031
INFO 2020-04-27 04:51:55,878 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:54:00,776 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 04:54:04,661 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 173, in put
    send_verify_email.dealy(email, verify_url)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'send_verify_email' object has no attribute 'dealy'
ERROR 2020-04-27 04:54:04,663 basehttp 154 "PUT /emails/ HTTP/1.1" 500 88878
INFO 2020-04-27 04:55:35,399 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 04:55:38,968 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 173, in put
    send_verify_email.dealy(email, verify_url)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/celery/local.py", line 146, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'send_verify_email' object has no attribute 'dealy'
ERROR 2020-04-27 04:55:38,971 basehttp 154 "PUT /emails/ HTTP/1.1" 500 88878
INFO 2020-04-27 04:56:41,241 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 04:56:41,838 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 04:56:45,354 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 04:59:47,788 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 04:59:48,269 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 04:59:53,408 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 04:59:53,409 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-04-27 04:59:53,421 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 05:01:38,948 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 05:01:38,957 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-04-27 05:01:38,966 basehttp 154 "GET /info/ HTTP/1.1" 200 151
INFO 2020-04-27 05:01:57,577 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-04-27 05:01:57,715 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 05:59:19,276 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 05:59:21,109 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 05:59:21,261 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 05:59:21,773 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 05:59:21,774 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4027
WARNING 2020-04-27 05:59:23,273 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 05:59:23,276 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4039
INFO 2020-04-27 05:59:23,284 basehttp 154 "GET /info/ HTTP/1.1" 200 151
INFO 2020-04-27 05:59:27,735 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-04-27 05:59:27,935 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 06:43:01,471 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:43:07,062 log 228 Not Found: /carts/
WARNING 2020-04-27 06:43:07,063 basehttp 154 "GET /carts/ HTTP/1.1" 404 4161
INFO 2020-04-27 06:43:11,123 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 06:43:11,125 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 06:43:11,131 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4194
WARNING 2020-04-27 06:43:14,300 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:43:14,318 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:44:32,270 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:44:51,528 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 06:44:51,531 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4194
INFO 2020-04-27 06:44:51,555 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 06:44:53,410 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:44:53,424 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:45:14,911 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:45:16,448 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 06:45:16,451 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4194
INFO 2020-04-27 06:45:16,481 basehttp 154 "GET /info/ HTTP/1.1" 200 151
WARNING 2020-04-27 06:45:17,632 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:45:17,657 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:45:59,324 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:46:00,647 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:46:00,654 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:46:30,383 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:46:31,715 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:46:31,718 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:47:08,236 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 06:47:12,135 log 228 Not Found: /addresses/
WARNING 2020-04-27 06:47:12,141 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 06:47:12,143 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 06:47:21,449 log 228 Not Found: /areas/110000/
WARNING 2020-04-27 06:47:21,450 basehttp 154 "GET /areas/110000/ HTTP/1.1" 404 4182
INFO 2020-04-27 07:10:18,176 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:10:21,305 log 228 Not Found: /addresses/
WARNING 2020-04-27 07:10:21,307 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4173
INFO 2020-04-27 07:10:21,320 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 07:10:26,618 log 228 Not Found: /areas/140000/
WARNING 2020-04-27 07:10:26,620 basehttp 154 "GET /areas/140000/ HTTP/1.1" 404 4182
INFO 2020-04-27 07:10:56,305 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:10:59,156 log 228 Not Found: /areas/130000/
WARNING 2020-04-27 07:10:59,160 basehttp 154 "GET /areas/130000/ HTTP/1.1" 404 4182
INFO 2020-04-27 07:12:31,161 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 07:12:35,366 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() got an unexpected keyword argument 'pk'
ERROR 2020-04-27 07:12:35,369 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 79784
INFO 2020-04-27 07:14:27,465 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 07:14:29,425 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 07:14:29,443 log 228 Not Found: /addresses/
WARNING 2020-04-27 07:14:29,446 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 07:15:01,337 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:15:15,139 log 228 Not Found: /addresses/
WARNING 2020-04-27 07:15:15,140 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 07:15:15,147 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 07:15:18,653 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2020-04-27 07:15:20,875 basehttp 154 "GET /areas/140300/ HTTP/1.1" 200 301
INFO 2020-04-27 07:15:36,078 basehttp 154 "GET /areas/141000/ HTTP/1.1" 200 853
INFO 2020-04-27 07:49:55,711 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:49:58,496 log 228 Not Found: /addresses/
WARNING 2020-04-27 07:49:58,503 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 07:49:58,511 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 07:50:35,474 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 07:50:49,380 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:50:54,723 log 228 Not Found: /addresses/
WARNING 2020-04-27 07:50:54,725 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 07:51:09,391 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 07:51:20,194 log 228 Not Found: /
WARNING 2020-04-27 07:51:20,195 basehttp 154 "GET / HTTP/1.1" 404 4297
WARNING 2020-04-27 07:51:20,326 log 228 Not Found: /favicon.ico
WARNING 2020-04-27 07:51:20,333 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 4348
INFO 2020-04-27 07:51:34,158 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 08:22:19,951 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 08:22:25,129 log 228 Not Found: /addresses/
WARNING 2020-04-27 08:22:25,131 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 08:22:25,137 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 08:22:28,782 basehttp 154 "GET /areas/120000/ HTTP/1.1" 200 45
INFO 2020-04-27 08:22:30,193 basehttp 154 "GET /areas/150000/ HTTP/1.1" 200 45
INFO 2020-04-27 08:23:12,316 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 08:23:15,929 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 08:23:15,945 log 228 Not Found: /addresses/
WARNING 2020-04-27 08:23:15,946 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 08:23:56,551 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 08:24:02,538 log 228 Not Found: /addresses/
WARNING 2020-04-27 08:24:02,544 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4351
INFO 2020-04-27 08:24:02,558 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 08:24:04,938 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2020-04-27 08:24:06,435 basehttp 154 "GET /areas/140100/ HTTP/1.1" 200 573
INFO 2020-04-27 09:31:28,193 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 09:31:30,795 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:31:30,796 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:31:30,801 basehttp 154 "GET /info/ HTTP/1.1" 200 142
INFO 2020-04-27 09:31:56,563 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-04-27 09:31:56,734 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-04-27 09:37:33,519 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:37:33,522 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:37:33,532 basehttp 154 "GET /info/ HTTP/1.1" 200 142
INFO 2020-04-27 09:37:35,363 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 09:40:41,330 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 09:45:38,923 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 09:52:08,912 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 09:52:12,456 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 09:52:12,601 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 09:52:13,124 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 09:52:13,126 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4360
WARNING 2020-04-27 09:52:15,440 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:52:15,443 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:52:15,449 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:52:25,173 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2020-04-27 09:52:25,253 log 228 Internal Server Error: /emails/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 172, in put
    verify_url = request.user.generate_access_token()
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py", line 35, in generate_access_token
    return dev.EMAIL_VERIFY_URL + token
NameError: name 'dev' is not defined
ERROR 2020-04-27 09:52:25,257 basehttp 154 "PUT /emails/ HTTP/1.1" 500 88979
INFO 2020-04-27 09:53:34,873 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/models.py changed, reloading.
INFO 2020-04-27 09:53:35,335 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 09:53:38,674 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
WARNING 2020-04-27 09:54:08,961 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:08,964 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:08,966 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:10,457 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:54:10,458 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:10,467 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 09:54:11,692 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:54:11,698 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:11,700 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 09:54:12,732 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:12,744 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:12,746 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:13,800 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:13,804 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:13,810 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:15,786 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:54:15,788 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:15,789 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:24,228 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:24,238 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:24,238 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:25,898 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:25,902 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:25,902 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 09:54:27,717 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:27,719 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:27,725 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:28,794 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:54:28,800 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:28,802 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 09:54:29,375 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:29,385 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:29,388 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:29,850 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:29,857 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:29,858 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:30,222 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:30,224 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:30,234 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:30,472 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:30,485 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:30,496 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:30,654 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:30,656 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:30,666 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:30,807 log 228 Not Found: /browse_histories/
INFO 2020-04-27 09:54:30,810 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:30,817 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 09:54:30,966 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:30,974 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:30,979 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:31,341 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:31,348 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:31,344 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:54:31,795 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:54:31,802 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:54:31,809 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:56:18,187 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:56:18,190 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:56:18,197 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:56:20,346 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:56:20,348 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:56:20,353 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:56:21,019 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:56:21,025 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:56:21,026 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 09:56:21,662 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 09:56:21,666 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 09:56:21,675 basehttp 154 "GET /info/ HTTP/1.1" 200 142
INFO 2020-04-27 09:58:07,530 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 10:00:13,087 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU4Nzk4MTIxOCwiZXhwIjoxNTg3OTgzMDE4fQ.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjEwMDc1NDUxMDNAcXEuY29tIn0.BOjwzUFkNOeVz-UG-GXUZmDsEll0kuKCvLiXx19HxkfMh16rBAxQlaAsb4tbvvK5cXAuMw_Q697FgUMbim0ung HTTP/1.1" 200 0
ERROR 2020-04-27 10:00:26,133 log 228 Internal Server Error: /emails/verification/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 184, in put
    user = check_access_token(token)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 20, in check_access_token
    return data['openid']
KeyError: 'openid'
INFO 2020-04-27 10:00:43,396 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 10:00:47,130 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 10:00:47,718 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 10:00:47,719 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4360
WARNING 2020-04-27 10:00:48,865 log 228 Not Found: /browse_histories/
INFO 2020-04-27 10:00:48,869 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 10:00:48,876 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
WARNING 2020-04-27 10:00:50,327 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 10:00:50,328 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 10:00:50,335 basehttp 154 "GET /info/ HTTP/1.1" 200 142
INFO 2020-04-27 10:02:43,771 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
INFO 2020-04-27 10:02:43,954 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 10:02:56,208 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU4Nzk4MTc2MywiZXhwIjoxNTg3OTgzNTYzfQ.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjEwMDc1NDUxMDNAcXEuY29tIn0.ZrzU5nEZR4Sq2lT5nV9oe22mOMWyHnwKmKF46ylWoEcVKSNSmyw4E2J1BPpgcPWtlDJvTrWW8h3EieNGPlmHRg HTTP/1.1" 200 0
ERROR 2020-04-27 10:02:56,310 log 228 Internal Server Error: /emails/verification/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 184, in put
    user = check_access_token(token)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/oauth/utils.py", line 20, in check_access_token
    return data['openid']
KeyError: 'openid'
ERROR 2020-04-27 10:02:56,313 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU4Nzk4MTc2MywiZXhwIjoxNTg3OTgzNTYzfQ.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjEwMDc1NDUxMDNAcXEuY29tIn0.ZrzU5nEZR4Sq2lT5nV9oe22mOMWyHnwKmKF46ylWoEcVKSNSmyw4E2J1BPpgcPWtlDJvTrWW8h3EieNGPlmHRg HTTP/1.1" 500 88013
WARNING 2020-04-27 10:03:03,581 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 10:03:03,583 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4360
WARNING 2020-04-27 10:03:07,190 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 10:03:07,191 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 10:03:07,195 basehttp 154 "GET /info/ HTTP/1.1" 200 142
WARNING 2020-04-27 10:03:09,090 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 10:03:09,097 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 10:03:09,104 basehttp 154 "GET /info/ HTTP/1.1" 200 142
INFO 2020-04-27 10:08:43,378 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 10:08:47,514 basehttp 154 "PUT /emails/ HTTP/1.1" 200 27
INFO 2020-04-27 10:09:01,671 basehttp 154 "OPTIONS /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU4Nzk4MjEyNywiZXhwIjoxNTg3OTgzOTI3fQ.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjEwMDc1NDUxMDNAcXEuY29tIn0.CZ7Pp6siOsuvEW3PK7d0Xna0A51OOkUNpQCOInAeh_Pl-v69SOd0yrgyO66FK_Aiyxly1rBLGt7njzEO2YZsJw HTTP/1.1" 200 0
INFO 2020-04-27 10:09:01,707 basehttp 154 "PUT /emails/verification/?token=eyJhbGciOiJIUzUxMiIsImlhdCI6MTU4Nzk4MjEyNywiZXhwIjoxNTg3OTgzOTI3fQ.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6IjEwMDc1NDUxMDNAcXEuY29tIn0.CZ7Pp6siOsuvEW3PK7d0Xna0A51OOkUNpQCOInAeh_Pl-v69SOd0yrgyO66FK_Aiyxly1rBLGt7njzEO2YZsJw HTTP/1.1" 200 27
INFO 2020-04-27 10:09:05,785 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-04-27 10:09:05,804 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 10:09:05,805 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4372
INFO 2020-04-27 15:53:59,258 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 15:55:04,418 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 15:55:06,211 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 15:55:06,371 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 15:55:06,862 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 15:55:06,863 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4526
WARNING 2020-04-27 15:55:08,657 log 228 Not Found: /browse_histories/
INFO 2020-04-27 15:55:08,658 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-04-27 15:55:08,662 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4538
WARNING 2020-04-27 15:55:11,148 log 228 Not Found: /addresses/
WARNING 2020-04-27 15:55:11,157 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 15:55:11,171 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 15:55:15,759 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2020-04-27 15:55:19,399 basehttp 154 "GET /areas/141000/ HTTP/1.1" 200 853
INFO 2020-04-27 15:55:54,865 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 15:55:55,979 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
INFO 2020-04-27 15:56:18,410 basehttp 154 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
INFO 2020-04-27 15:57:46,743 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 15:58:39,868 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 15:59:08,845 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 15:59:42,471 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:02:14,712 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:03:17,440 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:03:24,388 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 63
WARNING 2020-04-27 16:03:24,608 log 228 Not Found: /addresses/
INFO 2020-04-27 16:03:24,611 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:03:24,614 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:06:34,898 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 16:07:31,694 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:07:31,701 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:07:31,712 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 16:07:32,639 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:07:32,663 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:07:32,664 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:07:39,615 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 16:07:45,055 log 228 Internal Server Error: /areas/110000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:07:45,059 basehttp 154 "GET /areas/110000/ HTTP/1.1" 500 109326
INFO 2020-04-27 16:08:20,590 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:08:26,842 basehttp 154 "GET /areas/120000/ HTTP/1.1" 200 141
INFO 2020-04-27 16:08:27,933 basehttp 154 "GET /areas/120100/ HTTP/1.1" 200 837
ERROR 2020-04-27 16:08:29,646 log 228 Internal Server Error: /areas/110000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:08:29,649 basehttp 154 "GET /areas/110000/ HTTP/1.1" 500 107586
INFO 2020-04-27 16:09:10,274 basehttp 154 "GET /areas/130000/ HTTP/1.1" 200 701
INFO 2020-04-27 16:09:14,002 basehttp 154 "GET /areas/130200/ HTTP/1.1" 200 739
ERROR 2020-04-27 16:09:16,763 log 228 Internal Server Error: /areas/110000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:09:16,764 basehttp 154 "GET /areas/110000/ HTTP/1.1" 500 107586
INFO 2020-04-27 16:14:40,820 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:14:46,281 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:14:46,291 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:14:46,292 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
ERROR 2020-04-27 16:14:50,366 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:14:50,372 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 107586
ERROR 2020-04-27 16:14:55,801 log 228 Internal Server Error: /areas/120000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:14:55,802 basehttp 154 "GET /areas/120000/ HTTP/1.1" 500 107586
INFO 2020-04-27 16:17:45,214 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:17:49,991 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:17:50,007 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:17:50,007 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
WARNING 2020-04-27 16:17:51,256 log 228 Not Found: /addresses/
INFO 2020-04-27 16:17:51,258 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:17:51,261 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
ERROR 2020-04-27 16:17:54,038 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:17:54,041 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 110062
INFO 2020-04-27 16:20:24,588 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 16:20:26,969 log 228 Not Found: /addresses/
INFO 2020-04-27 16:20:26,975 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:20:26,977 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
ERROR 2020-04-27 16:20:31,079 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:20:31,081 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 110062
INFO 2020-04-27 16:21:00,143 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:21:19,947 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:26:04,748 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-04-27 16:26:11,844 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 16:26:11,845 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4526
INFO 2020-04-27 16:26:13,488 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-04-27 16:26:13,491 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 16:26:13,492 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4538
WARNING 2020-04-27 16:26:16,740 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:26:16,742 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:26:16,743 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
ERROR 2020-04-27 16:26:22,069 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/django_env/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:26:22,073 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 107586
INFO 2020-04-27 16:31:01,657 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:31:06,306 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:31:06,322 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:31:06,323 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
ERROR 2020-04-27 16:31:10,046 log 228 Internal Server Error: /areas/140000/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py", line 57, in get
    'sub_data':sub_data
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'type' is not JSON serializable
ERROR 2020-04-27 16:31:10,048 basehttp 154 "GET /areas/140000/ HTTP/1.1" 500 110062
INFO 2020-04-27 16:33:44,309 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/areas/views.py changed, reloading.
INFO 2020-04-27 16:33:44,958 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:33:46,817 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:33:56,207 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:34:58,348 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:35:19,583 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:35:23,665 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
WARNING 2020-04-27 16:35:23,679 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:35:23,682 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:35:26,826 basehttp 154 "GET /areas/140000/ HTTP/1.1" 200 601
INFO 2020-04-27 16:35:31,000 basehttp 154 "GET /areas/140200/ HTTP/1.1" 200 589
INFO 2020-04-27 16:36:01,704 basehttp 154 "OPTIONS /addresses/create/ HTTP/1.1" 200 0
ERROR 2020-04-27 16:36:01,833 log 228 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 262, in post
    address:dict
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
ERROR 2020-04-27 16:36:01,836 basehttp 154 "POST /addresses/create/ HTTP/1.1" 500 108303
ERROR 2020-04-27 16:36:03,569 log 228 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 262, in post
    address:dict
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be a string
ERROR 2020-04-27 16:36:03,571 basehttp 154 "POST /addresses/create/ HTTP/1.1" 500 108303
INFO 2020-04-27 16:37:04,547 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 16:37:05,046 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 16:37:08,940 log 228 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 262, in post
    'address':dict
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Area' is not JSON serializable
ERROR 2020-04-27 16:37:08,944 basehttp 154 "POST /addresses/create/ HTTP/1.1" 500 115039
INFO 2020-04-27 16:38:31,843 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 16:38:32,326 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:38:49,893 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:42:17,303 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 16:42:20,326 log 228 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 263, in post
    'address':dict
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Area' is not JSON serializable
ERROR 2020-04-27 16:42:20,330 basehttp 154 "POST /addresses/create/ HTTP/1.1" 500 115039
INFO 2020-04-27 16:43:17,827 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 16:43:18,288 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 16:43:21,160 log 228 Internal Server Error: /addresses/create/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 263, in post
    'address':address_dict
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/http/response.py", line 558, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/serializers/json.py", line 104, in default
    return super().default(o)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Area' is not JSON serializable
ERROR 2020-04-27 16:43:21,162 basehttp 154 "POST /addresses/create/ HTTP/1.1" 500 115515
INFO 2020-04-27 16:44:45,037 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 16:44:45,491 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 16:44:49,262 basehttp 154 "POST /addresses/create/ HTTP/1.1" 200 248
WARNING 2020-04-27 16:44:49,416 log 228 Not Found: /addresses/
WARNING 2020-04-27 16:44:49,433 basehttp 154 "GET /addresses/ HTTP/1.1" 404 4517
INFO 2020-04-27 16:44:49,436 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 17:02:30,630 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 17:02:32,900 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 17:02:33,031 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 17:02:33,535 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 17:02:33,540 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 4685
WARNING 2020-04-27 17:02:34,826 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 17:02:34,827 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 4697
INFO 2020-04-27 17:02:34,849 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-04-27 17:02:36,663 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 17:02:36,730 basehttp 154 "GET /addresses/ HTTP/1.1" 200 1537
INFO 2020-04-27 17:03:00,286 basehttp 154 "OPTIONS /addresses/1/ HTTP/1.1" 200 0
WARNING 2020-04-27 17:03:00,295 log 228 Not Found: /addresses/1/
WARNING 2020-04-27 17:03:00,295 basehttp 154 "DELETE /addresses/1/ HTTP/1.1" 404 4685
WARNING 2020-04-27 17:03:01,098 log 228 Not Found: /addresses/1/
WARNING 2020-04-27 17:03:01,099 basehttp 154 "DELETE /addresses/1/ HTTP/1.1" 404 4685
INFO 2020-04-27 19:13:03,778 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:13:23,208 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:13:23,236 basehttp 154 "GET /addresses/ HTTP/1.1" 200 1537
INFO 2020-04-27 19:13:27,211 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 19:13:28,372 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
INFO 2020-04-27 19:48:28,643 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:48:33,468 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:33,520 basehttp 154 "GET /addresses/ HTTP/1.1" 200 1537
INFO 2020-04-27 19:48:35,229 basehttp 154 "OPTIONS /addresses/1/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:35,243 basehttp 154 "DELETE /addresses/1/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:35,386 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:35,432 basehttp 154 "GET /addresses/ HTTP/1.1" 200 1327
INFO 2020-04-27 19:48:36,257 basehttp 154 "OPTIONS /addresses/7/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:36,270 basehttp 154 "DELETE /addresses/7/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:36,401 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:36,476 basehttp 154 "GET /addresses/ HTTP/1.1" 200 1117
INFO 2020-04-27 19:48:36,957 basehttp 154 "OPTIONS /addresses/6/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:36,975 basehttp 154 "DELETE /addresses/6/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:37,106 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:37,153 basehttp 154 "GET /addresses/ HTTP/1.1" 200 907
INFO 2020-04-27 19:48:37,619 basehttp 154 "OPTIONS /addresses/5/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:37,630 basehttp 154 "DELETE /addresses/5/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:37,769 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:37,830 basehttp 154 "GET /addresses/ HTTP/1.1" 200 697
INFO 2020-04-27 19:48:38,287 basehttp 154 "OPTIONS /addresses/4/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:38,299 basehttp 154 "DELETE /addresses/4/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:38,400 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:38,435 basehttp 154 "GET /addresses/ HTTP/1.1" 200 487
INFO 2020-04-27 19:48:38,918 basehttp 154 "OPTIONS /addresses/3/ HTTP/1.1" 200 0
INFO 2020-04-27 19:48:38,932 basehttp 154 "DELETE /addresses/3/ HTTP/1.1" 200 27
INFO 2020-04-27 19:48:39,057 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:48:39,069 basehttp 154 "GET /addresses/ HTTP/1.1" 200 277
INFO 2020-04-27 19:48:42,633 basehttp 154 "OPTIONS /addresses/2/default/ HTTP/1.1" 200 0
WARNING 2020-04-27 19:48:42,646 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 19:48:42,647 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
INFO 2020-04-27 19:48:58,434 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 19:48:59,506 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
INFO 2020-04-27 19:49:01,708 basehttp 154 "OPTIONS /addresses/2/ HTTP/1.1" 200 0
ERROR 2020-04-27 19:49:01,713 views 342 'Manager' object has no attribute 'fitter'
INFO 2020-04-27 19:49:01,714 basehttp 154 "PUT /addresses/2/ HTTP/1.1" 200 81
INFO 2020-04-27 19:49:54,898 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:50:04,639 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:50:04,660 basehttp 154 "GET /addresses/ HTTP/1.1" 200 277
INFO 2020-04-27 19:50:14,709 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 19:50:15,586 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
ERROR 2020-04-27 19:50:17,546 views 342 'Manager' object has no attribute 'fitter'
INFO 2020-04-27 19:50:17,547 basehttp 154 "PUT /addresses/2/ HTTP/1.1" 200 81
INFO 2020-04-27 19:51:01,923 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:51:01,976 basehttp 154 "GET /addresses/ HTTP/1.1" 200 277
INFO 2020-04-27 19:51:03,458 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 19:51:03,489 basehttp 154 "GET /addresses/ HTTP/1.1" 200 277
INFO 2020-04-27 19:51:39,101 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:52:23,646 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:52:30,762 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 19:52:32,108 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
INFO 2020-04-27 19:53:27,830 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 19:53:31,357 basehttp 154 "PUT /addresses/2/ HTTP/1.1" 200 254
INFO 2020-04-27 20:05:59,064 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:06:02,361 basehttp 154 "OPTIONS /addresses/2/default/ HTTP/1.1" 200 0
WARNING 2020-04-27 20:06:02,373 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:02,374 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:04,794 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:04,795 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
INFO 2020-04-27 20:06:06,256 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 20:06:06,283 basehttp 154 "GET /addresses/ HTTP/1.1" 200 283
WARNING 2020-04-27 20:06:08,007 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:08,008 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:08,757 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:08,758 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:09,280 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:09,281 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:09,843 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:09,844 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:10,274 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:10,275 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:10,691 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:10,691 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:11,083 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:11,084 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:11,522 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:11,523 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
WARNING 2020-04-27 20:06:12,361 log 228 Not Found: /addresses/2/default/
WARNING 2020-04-27 20:06:12,362 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 404 5076
INFO 2020-04-27 20:07:31,692 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-27 20:07:32,685 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:07:35,944 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 20:07:35,967 basehttp 154 "GET /addresses/ HTTP/1.1" 200 283
INFO 2020-04-27 20:07:37,768 basehttp 154 "PUT /addresses/2/default/ HTTP/1.1" 200 73
INFO 2020-04-27 20:07:37,907 basehttp 154 "GET /areas/ HTTP/1.1" 200 1772
INFO 2020-04-27 20:07:37,954 basehttp 154 "GET /addresses/ HTTP/1.1" 200 283
INFO 2020-04-27 20:08:38,081 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:08:45,947 basehttp 154 "GET /areas/110000/ HTTP/1.1" 200 141
INFO 2020-04-27 20:08:46,878 basehttp 154 "GET /areas/110100/ HTTP/1.1" 200 843
INFO 2020-04-27 20:08:55,910 basehttp 154 "OPTIONS /addresses/2/ HTTP/1.1" 200 0
INFO 2020-04-27 20:08:55,939 basehttp 154 "PUT /addresses/2/ HTTP/1.1" 200 254
INFO 2020-04-27 20:37:23,540 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:37:30,551 basehttp 154 "OPTIONS /addresses/2/title/ HTTP/1.1" 200 0
INFO 2020-04-27 20:37:30,567 basehttp 154 "PUT /addresses/2/title/ HTTP/1.1" 200 27
INFO 2020-04-27 20:51:47,977 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:52:37,071 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:52:57,903 basehttp 154 "OPTIONS /password/ HTTP/1.1" 200 0
WARNING 2020-04-27 20:52:57,914 log 228 Not Found: /password/
WARNING 2020-04-27 20:52:57,915 basehttp 154 "PUT /password/ HTTP/1.1" 404 5586
WARNING 2020-04-27 20:53:00,982 log 228 Not Found: /password/
WARNING 2020-04-27 20:53:00,983 basehttp 154 "PUT /password/ HTTP/1.1" 404 5586
INFO 2020-04-27 20:53:11,296 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/urls.py changed, reloading.
INFO 2020-04-27 20:53:11,754 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 20:53:15,826 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 415, in put
    old_password = dict('old_password')
TypeError: 'dict' object is not callable
ERROR 2020-04-27 20:53:15,829 basehttp 154 "PUT /password/ HTTP/1.1" 500 84631
ERROR 2020-04-27 20:53:17,132 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 415, in put
    old_password = dict('old_password')
TypeError: 'dict' object is not callable
ERROR 2020-04-27 20:53:17,133 basehttp 154 "PUT /password/ HTTP/1.1" 500 84631
ERROR 2020-04-27 20:53:18,088 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 415, in put
    old_password = dict('old_password')
TypeError: 'dict' object is not callable
ERROR 2020-04-27 20:53:18,089 basehttp 154 "PUT /password/ HTTP/1.1" 500 84631
ERROR 2020-04-27 20:53:18,639 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 415, in put
    old_password = dict('old_password')
TypeError: 'dict' object is not callable
ERROR 2020-04-27 20:53:18,640 basehttp 154 "PUT /password/ HTTP/1.1" 500 84631
ERROR 2020-04-27 20:53:19,132 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 415, in put
    old_password = dict('old_password')
TypeError: 'dict' object is not callable
ERROR 2020-04-27 20:53:19,133 basehttp 154 "PUT /password/ HTTP/1.1" 500 84631
INFO 2020-04-27 20:54:02,275 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:54:05,777 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
ERROR 2020-04-27 20:54:18,889 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:54:18,891 basehttp 154 "PUT /password/ HTTP/1.1" 500 89380
ERROR 2020-04-27 20:54:19,352 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:54:19,353 basehttp 154 "PUT /password/ HTTP/1.1" 500 89380
ERROR 2020-04-27 20:54:19,527 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:54:19,528 basehttp 154 "PUT /password/ HTTP/1.1" 500 89380
ERROR 2020-04-27 20:54:19,910 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:54:19,911 basehttp 154 "PUT /password/ HTTP/1.1" 500 89380
INFO 2020-04-27 20:55:48,240 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 20:55:50,504 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:55:50,505 basehttp 154 "PUT /password/ HTTP/1.1" 500 89381
ERROR 2020-04-27 20:55:51,496 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:55:51,498 basehttp 154 "PUT /password/ HTTP/1.1" 500 89381
INFO 2020-04-27 20:57:12,962 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 20:57:13,434 autoreload 597 Watching for file changes with StatReloader
ERROR 2020-04-27 20:57:16,499 log 228 Internal Server Error: /password/
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py", line 420, in put
    result = request.user.check_password(old_password)
  File "/home/ubuntu/.virtualenvs/meiduo_mall/lib/python3.6/site-packages/django/contrib/auth/models.py", line 400, in check_password
    raise NotImplementedError("Django doesn't provide a DB representation for AnonymousUser.")
NotImplementedError: Django doesn't provide a DB representation for AnonymousUser.
ERROR 2020-04-27 20:57:16,501 basehttp 154 "PUT /password/ HTTP/1.1" 500 89381
INFO 2020-04-27 20:58:32,498 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 20:58:33,016 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:58:35,801 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:36,811 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:42,951 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:43,494 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:52,322 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 20:58:55,721 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:56,313 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:56,489 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 20:58:56,681 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:01:49,440 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 21:01:50,018 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 21:01:57,936 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 21:02:31,417 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:32,501 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:33,336 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:33,934 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:35,353 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:35,855 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:36,339 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:02:36,792 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:36,418 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 21:03:39,074 basehttp 154 "OPTIONS /password/ HTTP/1.1" 200 0
INFO 2020-04-27 21:03:39,081 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:39,614 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:39,868 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:40,128 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:40,534 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:40,938 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:41,171 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:03:42,705 basehttp 154 "GET /info/ HTTP/1.1" 200 63
WARNING 2020-04-27 21:03:42,725 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 21:03:42,726 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5609
INFO 2020-04-27 21:03:45,767 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-04-27 21:03:45,880 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:03:47,415 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:03:57,066 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 21:03:57,505 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:03:57,506 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:04:00,081 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 21:04:00,083 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5609
INFO 2020-04-27 21:04:00,092 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-04-27 21:04:21,819 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:04:52,982 basehttp 154 "PUT /password/ HTTP/1.1" 200 63
INFO 2020-04-27 21:04:54,623 basehttp 154 "GET /info/ HTTP/1.1" 200 63
WARNING 2020-04-27 21:04:54,643 log 228 Not Found: /browse_histories/
WARNING 2020-04-27 21:04:54,645 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5609
INFO 2020-04-27 21:04:57,289 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:05:37,239 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/users/views.py changed, reloading.
INFO 2020-04-27 21:05:37,936 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 21:05:39,141 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:05:51,513 autoreload 597 Watching for file changes with StatReloader
INFO 2020-04-27 21:05:53,060 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:05:58,162 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 21:05:58,722 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:05:58,725 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:06:00,148 log 228 Not Found: /browse_histories/
INFO 2020-04-27 21:06:00,161 basehttp 154 "GET /info/ HTTP/1.1" 200 141
WARNING 2020-04-27 21:06:00,163 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 5609
INFO 2020-04-27 21:06:42,196 basehttp 154 "PUT /password/ HTTP/1.1" 200 61
INFO 2020-04-27 21:06:47,089 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:07:17,938 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-04-27 21:07:23,136 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-04-27 21:07:23,628 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:23,629 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:51,277 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:51,278 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:51,937 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:51,940 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:52,560 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:52,562 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:53,185 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:53,191 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:54,671 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:54,672 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:07:55,403 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:07:55,406 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-04-27 21:08:07,129 log 228 Not Found: /carts/simple/
WARNING 2020-04-27 21:08:07,132 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
INFO 2020-05-04 14:21:10,502 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-04 14:22:28,023 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:22:28,030 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-05-04 14:22:35,076 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:22:35,078 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
WARNING 2020-05-04 14:22:49,880 log 228 Not Found: /list/157/skus/
WARNING 2020-05-04 14:22:49,921 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 404 5649
WARNING 2020-05-04 14:22:49,932 log 228 Not Found: /hot/157/
WARNING 2020-05-04 14:22:49,939 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:22:49,942 basehttp 154 "GET /hot/157/ HTTP/1.1" 404 5582
WARNING 2020-05-04 14:22:49,960 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5597
INFO 2020-05-04 14:27:41,129 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-04 14:28:23,446 autoreload 217 /home/ubuntu/Desktop/django预习/hfad_python/meiduo_mall/meiduo_mall/meiduo_mall/apps/goods/utils.py changed, reloading.
INFO 2020-05-04 14:28:24,847 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-04 14:28:29,590 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:29,591 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:29,654 basehttp 154 "GET /hot/157/ HTTP/1.1" 200 477
INFO 2020-05-04 14:28:29,733 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 591
INFO 2020-05-04 14:28:34,105 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 591
WARNING 2020-05-04 14:28:34,211 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:34,215 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:34,304 basehttp 154 "GET /hot/157/ HTTP/1.1" 200 477
WARNING 2020-05-04 14:28:36,140 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:36,178 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:36,193 basehttp 154 "GET /hot/157/ HTTP/1.1" 200 477
INFO 2020-05-04 14:28:36,206 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 591
WARNING 2020-05-04 14:28:37,601 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:37,615 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:37,642 basehttp 154 "GET /hot/157/ HTTP/1.1" 200 477
INFO 2020-05-04 14:28:37,643 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 591
WARNING 2020-05-04 14:28:39,016 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:39,038 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:39,062 basehttp 154 "GET /list/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 591
INFO 2020-05-04 14:28:39,078 basehttp 154 "GET /hot/157/ HTTP/1.1" 200 477
WARNING 2020-05-04 14:28:43,037 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:43,041 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:28:53,279 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:28:53,316 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:28:53,369 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-04 14:28:53,370 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
INFO 2020-05-04 14:28:56,293 basehttp 154 "GET /list/115/skus/?page=2&page_size=5&ordering=-create_time HTTP/1.1" 200 1487
INFO 2020-05-04 14:28:57,853 basehttp 154 "GET /list/115/skus/?page=3&page_size=5&ordering=-create_time HTTP/1.1" 200 1155
INFO 2020-05-04 14:29:01,192 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-04 14:29:01,231 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:01,238 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:01,356 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:01,358 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:10,418 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:10,420 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:10,445 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:10,447 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:11,416 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:11,445 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:11,462 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:11,463 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:11,943 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:11,953 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:11,959 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:11,965 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:13,058 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:13,059 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:13,095 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:13,098 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:13,856 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:13,862 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:13,881 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:13,927 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:29:15,233 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:29:15,239 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:29:15,243 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:15,246 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:29:47,219 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-05-04 14:29:47,396 basehttp 154 "POST /login/ HTTP/1.1" 200 75
INFO 2020-05-04 14:29:56,262 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-05-04 14:29:57,638 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:29:57,638 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:30:03,647 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:30:03,692 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:30:03,724 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
INFO 2020-05-04 14:30:03,725 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
WARNING 2020-05-04 14:30:05,615 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:30:05,622 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:30:05,630 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
WARNING 2020-05-04 14:30:05,657 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:32:04,454 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-04 14:32:15,103 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:32:15,155 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:32:24,002 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:32:24,007 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:32:24,010 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
INFO 2020-05-04 14:32:24,041 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-04 14:32:26,231 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-04 14:32:26,316 log 228 Not Found: /browse_histories/
WARNING 2020-05-04 14:32:26,352 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:32:26,357 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:32:26,378 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 5976
INFO 2020-05-04 14:35:57,246 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-04 14:36:04,923 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:36:04,963 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
WARNING 2020-05-04 14:36:06,200 log 228 Not Found: /carts/simple/
WARNING 2020-05-04 14:36:06,207 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 5963
INFO 2020-05-04 14:36:06,271 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-05 02:12:47,214 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-05 02:14:20,613 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 02:14:20,615 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 02:14:27,329 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 02:14:27,331 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 02:18:33,817 basehttp 154 "GET /search/?q=%E6%89%8B%E6%9C%BA&page=1&page_size=6 HTTP/1.1" 200 4568
WARNING 2020-05-05 02:18:49,891 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 02:18:49,896 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 02:18:49,920 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-05 02:18:49,960 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 02:18:49,961 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 02:19:15,452 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 02:19:15,468 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 02:19:30,516 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-05 02:19:36,816 basehttp 154 "GET /search/?q=apple&page=1&page_size=6 HTTP/1.1" 200 2333
INFO 2020-05-05 02:21:47,009 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-05 02:21:52,063 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 02:21:52,065 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 02:21:54,382 basehttp 154 "GET /search/?q=apple&page=1&page_size=6 HTTP/1.1" 200 1422
INFO 2020-05-05 02:23:27,971 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-05 04:27:14,902 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:27:14,910 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:23,575 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:23,582 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 04:28:23,691 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-05 04:28:37,080 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-05 04:28:43,610 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
WARNING 2020-05-05 04:28:43,628 log 228 Not Found: /carts/simple/
INFO 2020-05-05 04:28:43,631 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
WARNING 2020-05-05 04:28:43,632 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:48,909 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:48,910 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 04:28:48,914 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-05 04:28:48,963 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:28:48,964 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:28:51,177 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:28:51,181 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:28:51,186 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:51,187 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:52,491 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:28:52,501 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:52,503 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:28:52,513 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:53,564 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:28:53,575 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:28:53,577 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:53,578 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:54,189 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:28:54,208 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:28:54,209 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:28:54,212 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:24,221 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:24,225 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:24,227 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:24,228 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:25,512 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:25,517 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:25,518 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:25,519 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:26,693 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:26,700 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:26,708 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:26,708 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:28,319 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:28,327 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:28,328 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:28,334 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:29,548 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:29,566 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:29,568 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:29,573 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:30,081 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:30,086 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:30,088 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:30,090 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:30,890 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:30,910 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:30,916 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:30,922 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:31,333 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:31,337 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:31,341 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:31,342 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:32,589 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:32,594 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:32,595 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:32,596 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:33,716 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:33,721 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:33,725 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:33,731 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:34,656 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:34,667 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:34,667 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:34,673 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:35,073 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:35,067 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:35,074 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:35,075 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:35,839 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:35,846 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:35,848 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:35,848 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 04:29:43,525 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 04:29:43,526 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 04:29:43,536 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 04:29:43,537 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 13:07:25,333 autoreload 597 Watching for file changes with StatReloader
WARNING 2020-05-05 13:09:52,279 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:09:52,280 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 13:09:55,062 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
INFO 2020-05-05 13:09:55,067 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2020-05-05 13:09:56,926 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-05-05 13:09:57,151 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-05-05 13:09:57,861 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:09:57,862 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:00,873 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:00,874 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 13:10:00,889 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-05 13:10:00,893 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
INFO 2020-05-05 13:10:04,469 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-05 13:10:04,483 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:04,487 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:04,521 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:04,523 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:11,304 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:11,308 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:11,322 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:11,322 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:12,784 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:12,794 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:12,801 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:12,802 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:13,596 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:13,598 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:13,608 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:13,609 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:14,399 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:14,404 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:14,402 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:14,410 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:15,226 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:15,227 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:15,239 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:15,240 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:16,252 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:16,256 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:16,258 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:16,259 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:16,638 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:16,648 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:16,649 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:16,649 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:17,066 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:17,068 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:17,080 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:17,081 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
WARNING 2020-05-05 13:10:17,502 log 228 Not Found: /browse_histories/
WARNING 2020-05-05 13:10:17,504 basehttp 154 "POST /browse_histories/ HTTP/1.1" 404 6132
WARNING 2020-05-05 13:10:17,512 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 13:10:17,512 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6119
INFO 2020-05-05 14:19:05,973 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-05 14:19:28,561 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2020-05-05 14:19:28,741 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2020-05-05 14:19:29,559 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:29,562 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
WARNING 2020-05-05 14:19:32,770 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:32,778 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:32,820 basehttp 154 "GET /hot/115/ HTTP/1.1" 200 582
INFO 2020-05-05 14:19:32,822 basehttp 154 "GET /list/115/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 200 1561
INFO 2020-05-05 14:19:34,224 basehttp 154 "OPTIONS /browse_histories/ HTTP/1.1" 200 0
WARNING 2020-05-05 14:19:34,236 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:34,237 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:34,282 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
WARNING 2020-05-05 14:19:36,492 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:36,493 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:36,501 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
WARNING 2020-05-05 14:19:38,080 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:38,082 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:38,094 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
WARNING 2020-05-05 14:19:38,893 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:38,897 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:38,916 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
WARNING 2020-05-05 14:19:39,526 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:39,544 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:39,554 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
WARNING 2020-05-05 14:19:40,123 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:40,127 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:19:40,139 basehttp 154 "POST /browse_histories/ HTTP/1.1" 200 29
INFO 2020-05-05 14:19:48,880 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-05-05 14:19:48,902 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 1451
WARNING 2020-05-05 14:19:56,824 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:19:56,825 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
WARNING 2020-05-05 14:19:58,740 log 228 Not Found: /carts/
WARNING 2020-05-05 14:19:58,744 basehttp 154 "GET /carts/ HTTP/1.1" 404 6264
INFO 2020-05-05 14:20:02,612 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-05-05 14:20:02,663 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 1451
WARNING 2020-05-05 14:20:33,849 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:20:33,850 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:20:57,142 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-05-05 14:20:57,161 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 1451
INFO 2020-05-05 14:21:28,445 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-05 14:21:32,326 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-05-05 14:21:32,349 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 1451
WARNING 2020-05-05 14:21:38,085 log 228 Not Found: /carts/simple/
WARNING 2020-05-05 14:21:38,087 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 6285
INFO 2020-05-05 14:22:16,178 autoreload 597 Watching for file changes with StatReloader
INFO 2020-05-05 14:22:21,370 basehttp 154 "GET /info/ HTTP/1.1" 200 141
INFO 2020-05-05 14:22:21,389 basehttp 154 "GET /browse_histories/ HTTP/1.1" 200 1168
